---
- name: Enable SwayNotificationCenter COPR Repository
  become: true
  community.general.copr:
    host: copr.fedorainfracloud.org
    state: enabled
    name: erikreider/SwayNotificationCenter
- name: Add Brave Browser Repository
  become: true
  ansible.builtin.get_url:
    url: "https://brave-browser-apt-release.s3.brave.com/brave-browser.repo"
    dest: /etc/yum.repos.d/brave-browser.repo
    mode: "0644"
    owner: root
    group: root
- name: Import Brave Browser Public Key
  become: true
  ansible.builtin.apt_key:
    state: present
    key: "https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg"
- name: Install Desktop Packages
  become: true
  ansible.builtin.apt:
    name:
      - firefox 
      - sway
      - swaylock
      - wofi
      - waybar
      - swayidle
      - grimshot
      - SwayNotificationCenter
      - alacritty
      - gammastep
      - brightnessctl
      - linux-libertine-fonts
      - google-noto-emoji-color-fonts
      - fontawesome-fonts
      - fontawesome-fonts-web
      - fontawesome5-fonts
      - fontawesome5-free-fonts
      - brave-browser
      - openvpn
    state: present
    update_cache: true
- name: Install Desktop Flatpaks
  community.general.flatpak:
    name:
      - org.signal.Signal
    method: user
    state: present
# NOTE: gpgv is not working properly :(
# - name: Validate Browserpass Native Signature
#   ansible.builtin.command: gpgv /tmp/browserpass-linux64.tar.gz.asc
#   when: not browserpass_result.stat.exists
#   register: pass_gpgv
#   failed_when: pass_gpgv.rc != 0
#   changed_when: false
- name: Unpack Browserpass Native
  ansible.builtin.unarchive:
    src: /tmp/browserpass-linux64.tar.gz
    dest: /tmp/
  when: not browserpass_result.stat.exists
- name: Install Browserpass Native
  become: true
  ansible.builtin.shell: |
    make BIN=browserpass-linux64 configure
    make BIN=browserpass-linux64 install
  args:
    chdir: /tmp/browserpass-linux64-3.1.0/
  when: not browserpass_result.stat.exists
  changed_when: true
- name: Install Desktop Configurations
  ansible.builtin.copy:
    src: files/config/
    dest: "{{ ansible_env.HOME }}/.config/"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: preserve
- name: Add Bash Dotfiles
  ansible.builtin.copy:
    src: " {{ item.src }} "
    dest: " {{ item.dst }} "
    loop: 
      - src: files/.bashrc
        dst: "{{ ansible_env.HOME }}"
      - src: files/.bash_aliases
        dst: "{{ ansible_env.HOME }}"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: preserve
- name: Enable Gammastep Service
  ansible.builtin.systemd:
    name: "gammastep.service"
    scope: "user"
    enabled: true
    daemon_reload: true
- name: Enable Notification Center Service
  ansible.builtin.systemd:
    name: "swaync.service"
    scope: "user"
    enabled: true
    daemon_reload: true
- name: Download Desktop Wallpaper
  ansible.builtin.get_url:
    url: https://wallpaperaccess.com/download/orange-polygon-692137
    dest: "{{ ansible_env.HOME }}/Pictures/orange-polygon-material-wallpaper.png"
    mode: "0644"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
- name: Link Current Wallpaper
  ansible.builtin.file:
    src: "{{ ansible_env.HOME }}/Pictures/orange-polygon-material-wallpaper.png"
    dest: "{{ ansible_env.HOME }}/Pictures/desktop-background"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: "0600"
    state: link
- name: Updating fontconfig cache
  ansible.builtin.command: fc-cache -f
  changed_when: true
